### PR TITLE
First attempt to get PHP 8.0 support

### PR DESCRIPTION
**Pull request by GwynethLlewelyn**
Hello all,

This is my first pull request here — and quite a big one!

My testing environment is Ubuntu 20.04.2 LTS, Linux kernel 5.4.0-72-generic, running inside an `nginx` 1.19.6 vhost (no special configuration needed) with PHP 8.0.3 running as PHP-FPM, and using MariaDB 10.4.18 as the database server (I also use macOS to do simple syntax checking, but, so far, I haven't tried it out on the Mac).

There are a few glitches here and there, but I managed to do an install from scratch and get all the basics working except for the ticketing system, which is still throwing errors even on a clean database and doesn't seem to like new tickets.

It includes an upgrade to the last PEAR DB version that was released; it's been obsolete for several years now, but at least it still works with PHP 8.0.

I admit being partial to the `??` [Null Coalescing Operator](https://www.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce) and tend to overuse it — before forgetting that it was just introduced in PHP 7. In other words, it's highly unlikely that this code will ever run on anything below PHP 7, but if full compatibility with PHP 5.6 is a _requirement_ (duh!), I could theoretically do a `regex` on the whole code to get rid of `??`...

Mind you, it'll take quite a lot of time to do a full review of all the code. I tried to document as much as possible, but feel free to ask if there are any doubts about some of my decisions.

I'm also aware that it's good GitHub etiquette to PGP-sign all commits submitted for inclusion in a pull request. Alas, for some reason, my favourite code editor seems to be unable to sign those commits, when I invoke `git` from inside it. Running `git` from the command line has no such problem. I haven't yet figured out what's wrong with my setup, but I hope to be able to fix it sooner or later.

Last but not least, I'm not really a professional programmer, and I often prefer easier-to-read code as opposed to very terse, idiomatic PHP-isms (except for the ternary operators... which I'm abusing all the time). In my experience, relying on those PHP-isms means that some things stop working after a few major versions; for example, the idiomatic `if ($variable) { ... }` to check if that variable exists, has been initialised, and doesn't have a value that equates to 0, `null`, `false`, `""`, `[]`, and so forth, has been over-used for _decades_ and is a relic of the time that PHP was purely interpreted. These days, with highly effective Just-In-Time compiling, the PHP team is turning PHP into a stricter language — which means that they can compile it much more efficiently — at the cost of forcing programmers to drop some of their more idiomatic PHP-isms. There is no end to this discussion, of course, and I'm not even taking sides (as said before, I've always _loved_ strongly-typed languages, and that's why I'm doing everything in Go these days), but keep that in mind when you see quite a _lot_ of extra non-idiomatic checks sprinkled all over the code. The goal was reaching a point where not even warnings are thrown!

### CODE REVIEW

**Comment by GwynethLlewelyn** [comment]
All right... I had a problem, I did a global search for all instances of `list [...] each()` (obsolete and deprecated) and manually changed all of them... but I forgot to take into account the many instances of `@each()` (the `@` being probably a previous attempt at preventing errors — an approach which might have worked until, uh, 5.6 — but which has been turned into a new error instead...

I think I've managed to change _all_ those instances of `@each()` to be turned into the equivalent `foreach (...)`... hopefully I caught them all _without_ breaking everything...

**Comment by ajdonnison** [comment]
@GwynethLlewelyn in terms of PHP version compatibility the https://w3techs.com/technologies/details/pl-php site suggests that a third of sites are still using versions of PHP 5, although I have no problem in suggesting a minimum version of 7 - provided we have a clear way of upgrading existing sites - which may mean some work in the installer to detect outdated versions and suggest upgrading PHP before continuing with the upgrade.

**Comment by ajdonnison** [comment]
One thing I have set up locally is `docker-compose` so that I can test various versions of PHP.  If you give me a day or two I'll run up some versions to test against.

**Comment by wgaylord** [comment]
I am very interested in this pull request.  Because at work we use ticketsmith and its to where we need to update PHP for one system we use but ticketsmith fails under that update. (With the same error as in #72 ) I haven't talked with my manager about trying the fix from that issue yet but if this gets merged this might be a better fix.

**Comment by GwynethLlewelyn** [comment]
I wonder if anyone had time to take a look at the whole PR?... I know, it's horribly long. Worse, I'm planning to add a few more changes in the probably-not-so-distant-future lol

**Comment by ipeevski** [comment]
I've been looking through the code changes as they've been coming through
and all looks reasonable, but haven't taken it for a spin or anything ...

**Comment by GwynethLlewelyn** [comment]
@ipeevski thanks for that! Aye, I'm aware that there is a _lot_ of code to review... it still has many issues here and there, broken functionality, and so forth... and I even haven't started to take a look [at known vulnerabilities](https://nmap.org/search.html?cx=partner-pub-0078565546631069%3Abx60rb-fytx&cof=FORID%3A9&ie=ISO-8859-1&q=dotproject&sa=Site+Search), some of which are around since 2012...

**Comment by tonymurray** [comment]
In calendar.class.php, line 527, I added 'static' before function getRecurrentEventforPeriod:
static function getRecurrentEventforPeriod($start_date, $end_date, $event_start_date, $event_end_date)

Similar to the fix you made on line 597. Does that make sense?- at least it fixed a Fatal error for me. Thanks for your previous work.

**Comment by GwynethLlewelyn** [comment]
Thanks, @tonymurray — I'm pretty sure I'm missing a lot of `static` keywords here and there. I fully admit that I haven't tried out _all_ of dotProject's functionality, so, no wonder here and there a few fatal errors are thrown...

BTW, PHP 8.1 is out, but I haven't tried to run dotProject under it. Let's see if there are many breaking changes...

**Comment by GwynethLlewelyn** [comment]
Huh... I wonder if there's something else I should change on the code to get this PR merged?

Maybe testing it under PHP 8.1...?

**Comment by fatabek** [comment]
Thanks for for this good working, we try today first time. 

1) When we click any options for example "write config" or "Install db & write config" Installlation not working but we have PHP 7.4 version installation. We use PHP 7.4 version config.php and databeses files. Can you check this ?
2) When we try to see gantt chart, if the project owner and the login user aren't same gantt chart doesn't display. Can you check this ? (We try PHP version 8 & 8.1)

Note : We use devel branch

**Comment by GwynethLlewelyn** [comment]
Ouch... I'm sorry, I haven't kept up with this lately!

**Comment by ajdonnison** [comment]
@GwynethLlewelyn Do you have any issues if I merge this pull request, or have I left it too long?

**Comment by GwynethLlewelyn** [comment]
@ajdonnison I'd be proud of it! 💯 

Give me just a couple of hours or so, because I'm trying to get a few dependencies right, based on some feedback I've got.

**Comment by ajdonnison** [comment]
@GwynethLlewelyn no problem, let me know when you think you are ready - doesn't have to be perfect at this stage as it is going into devel branch.  Once it is in we can then assess how close we are to cutting a new release.

**Comment by GwynethLlewelyn** [comment]
You're right! I keep trying to fix more and more things to make sure it's "perfect" but it never is.

So, please, go ahead with the merge :)

My next step will be to replace some of the ancient vendor libraries in an attempt to get ACL working again as before, as well as a few other annoying things that (hopefully) newer libraries ought to fix.

**Comment by GwynethLlewelyn** [comment]
And here we goooooo :) Thanks, Adam!

**Pull request merged**
