### PR TITLE
Switching to "color" input type form to change projects color

### PR DESCRIPTION
**Pull request by teodorg**
"Upgrading" the form for handling project colors to the HTML5 form type "color". In addition to making the code HTML5-friendly, we also get rid of some Javascript code and a solid amount of concats in the entire codebase that add the "#" symbol to all background styles. Instead the html color is saved in the database directly with the "#" in front of it.

### CODE REVIEW

**Comment by teodorg** [comment]
Added the "autofocus" attribute to the first fields of forms and search forms. Looks nicer and makes the system somehow more comfortable to work with.

**Comment by teodorg** [comment]
Changed the search forms from "text" to "search" type.

**Comment by benletchford** [comment]
Do we still need `dotProject/modules/public/color_selector.php` after this?

**Comment by teodorg** [comment]
Hmmm, looks like - no, we do not.

**Comment by teodorg** [comment]
So, are these changes going to be merged into the devel branch or rejected? Any suggestions on the commits ?

**Pull request merged**
